name: rtwb_n_reviewed

# https://crontab.guru/
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'
  push:
    branches:
      main

jobs: 
  scrape_it:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GDRIVE_PAT: ${{ secrets.GDRIVE_LONGTOKEN }}
      GDRIVE_USER: ${{ secrets.GDRIVE_USER }}
      
    steps:
    - name: Check out GH repository
      uses: actions/checkout@v3
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::googledrive
          any::googlesheets4
          any::rvest
          any::dplyr
        
    - name: Scrape with R script
      run: Rscript "scrape_rtwb.R"
      
